Generate new longer server key and new certificate
Since Fedora 33 the RSA keys needs to be 2048 bits or longer

https://fedoraproject.org/wiki/Changes/StrongCryptoSettings2

Used the following command with default answers to all questions

  openssl req -newkey rsa:2048 -nodes -keyout server.key -x509 -days 3650 -out server.crt

With the old key some of the tests were failing

  1) ProxyProtocol "before each" hook for "should decode an IPv4 proxy protocol header and use it as remoteAddress (NON-TLS)":
     Error: error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small

  2) Session "before each" hook for "should use 2775 or 3550 as default port":
     Error: error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small